# Configuration for Yasb (Yet Another Status Bar)
# Author: @ljzh04
# Last updated: 21/08/4

watch_stylesheet: true
watch_config: true

bars:
  yasb-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark: false
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:   ["user_button","plus","browser","explorer","terminal"]
      center: ["komorebi_workspaces"]
      right:  ["active_window","komorebi_active_layout","app_tray","wifi", "battery-widget","clock"]

widgets:
  battery-widget:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "{icon}"
      label_alt: "{percent}% | remaining: {time_remaining}"
      update_interval: 3000
      charging_options:
        icon_format: "{charging_icon}{icon}"
        blink_charging_icon: True
      status_thresholds:
        critical: 10
        low: 25
        medium: 75
        high: 95
        full: 100
      status_icons:
        icon_charging: "\udb80\ude41"
        icon_critical: "\uf244"
        icon_low: "\uf243"
        icon_medium: "\uf242"
        icon_high: "\uf241"
        icon_full: "\uf240"
      callbacks:
        on_left: "toggle_label" 
        on_middle: "do_nothing"
        on_right: "do_nothing"

  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[process][username]}"
      label_alt: "{win[process][username]}"
      label_no_window: "{win[process][username]}"
      max_length: 48
      max_length_ellipsis: "..."
      monitor_exclusive: true

  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      time_remaining_natural: true

  clock:
    type: "yasb.clock.ClockWidget"
    options:
        label: "{%I:%M %p}"
        label_alt: "{%a %b %d,%Y %H:%M:%S %Z}"
        timezones: ["Asia/Singapore", "Europe/London"]
        callbacks:
          on_middle: "exec explorer.exe shell:Appsfolder\\Microsoft.WindowsAlarms_8wekyb3d8bbwe!App"
          on_right: "next_timezone"

  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "\uf200 {info[histograms][cpu_percent]}"
      label_alt: "\uf200 CPU: {info[percent][total]}% | freq: {info[freq][current]:.2f} Mhz"
      update_interval: 500
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 10

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
        label: "\udb80\udf5b {virtual_mem_free}"
        label_alt: "\udb80\udf5b {virtual_mem_percent}%"
        update_interval: 5000
        callbacks:
          on_right: "exec cmd /c Taskmgr"

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: ""
        label_workspace_btn: "{index}"
        label_default_name: "{index}"
        label_zero_index: false
        hide_empty_workspaces: false

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: false
      label: "{icon}"
      layout_icons:
        bsp: "|bsp|"
        columns: "|columns|"
        rows: "|rows|"
        vertical_stack: "|vertical|"
        horizontal_stack: "|horizontal|"
        ultrawide_vertical_stack: "|ultra|"
        monocle: "|monocle|"
        maximised: "|maximised|"
        floating: "|floating|"
        paused: "|paused|"
      callbacks:
        on_left: 'next_layout'
        on_middle: 'toggle_monocle'
        on_right: 'prev_layout'

  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
        label: "{wifi_icon}"
        label_alt: "{wifi_icon} {wifi_name}"
        update_interval: 5000
        wifi_icons:
          - "\udb81\udf83"  # 0% strength (no wifi)
          - "\udb82\udcbf"  # 1-25% strength
          - "\udb82\udcbc"  # 26-50% strength
          - "\udb82\udcbd"  # 51-75% strength
          - "\udb82\udcbe"  # 76-100% strength. Alternate theming: \uf1eb
        callbacks:
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network"

  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\ueb01 \udb80\uddda {download_speed} | \udb81\udd52 {upload_speed}"
      label_alt: "\ueb01 \udb81\udd52 {upload_speed} | \udb80\uddda {download_speed}"
      update_interval: 1000 # Update interval should be a multiple of 1000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

  # Some custom widgets

  explorer:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf114 [e]"
      label_alt: ""
      class_name: "explorer-widget"
      exec_options:
        run_once: true
      callbacks:
        on_left: "exec explorer.exe"
        on_right: ""
  app_tray:
    type: "yasb.custom.CustomWidget"
    options: 
      label: "\udb80\udc4a"
      label_alt: ""
      class_name: "app_tray-widget"
      callbacks:
        on_left: "exec cmd /c %USERPROFILE%/Hide_System_Tray.ahk"
        on_right: "exec cmd /c %USERPROFILE%/Show_System_Tray.ahk"

  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf3c5 {data[city]}, {data[region]}"
      label_alt: "\uf3c5 {data[ip]} [{data[country]}]"
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000                                        # every 5 minutes
        return_format: "json"
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl"                           # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]} " # open ipinfo in browser

  weather:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf0c2 {data[current_condition][0][temp_C]}\u00b0c"
      label_alt: "\uf0c2 {data[current_condition][0][weatherDesc][0][value]}"
      class_name: "weather-widget"
      exec_options:
        run_cmd: "curl.exe  wttr.in/Vancouver?format=j1"
        # run every hour
        run_interval: 3600000
        return_format: "json"
  user_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue70f"
      label_alt: "Apps"
      class_name: "user_button-widget"
      callbacks:
        on_left: "exec cmd /c %USERPROFILE%/Show_Start_Menu.ahk"

  terminal:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uf489 [Enter]"
      label_alt: ""
      class_name: "terminal-widget"
      callbacks:
        on_left: "exec wt cmd /k fastfetch"

  browser:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\udb80\ude39 [b]"
      label_alt: ""
      class_name: "browser-widget"
      callbacks:
        on_left: "exec powershell /c start floorp"
  plus:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\uea60"
      label_alt: ""
      class_name: "plus-widget"
      callbacks:
        on_left: ""
  komorebic_ahk:
    type: "yasb.custom.CustomWidget"
    options:
      label: "KOMOREBI \uf2d4 [q] \udb81\udc50 [Q]"
      label_alt: ""
      class_name: "komorebi_ahk-widget"
      callbacks:
        on_left: ""